### ISSUE TITLE
Do not the Arabic file names appear?

### ISSUE THREAD

**Issue by eArabic** [epic-crap-app-designer/ECAD-PHP-File-Hub#1]
Hello
Thank you very much for this wonderful quick light script.
I have a problem that the file names do not appear in Arabic and appear in a long line only.
Please fix this problem and thank you very much.

![yyy](https://user-images.githubusercontent.com/24383546/34978407-2bbe2238-faaf-11e7-8983-9b714b09e129.png)

**Comment by eArabic** [comment]
Please add the file preview feature, especially the images and text files or php files and edit them ...
Adding the Edit Text Files option, editing files is necessary in file sharing.

**Comment by epic-crap-app-designer** [comment]
just read your issue. I have added an option that lets you choose if you want to allow all characters in filenames by setting $allowAllCharactersInObjectNames to true

tell me if your problem is now solved. It at least worked on my machine

**Comment by eArabic** [comment]
Hello dear friend
Thank you so much that the problem has been resolved and the name has been shown correctly.
